import { PrismicPreview } from '@prismicio/next';
import './globals.css';
import { Inter } from 'next/font/google';
import { repositoryName } from '@/prismicio';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-[1200px] mx-auto">
          {children}
          <PrismicPreview repositoryName={repositoryName} />
        </div>
      </body>
    </html>
  );
}
